### ISSUE TITLE
Statistics in Report Mixed Up

### ISSUE THREAD

**Issue by LukasGoetz** [AG-Boerries/MIRACUM-Pipe#14]
Hi,
statistics about nof mapped reads in the germline and tumor alignment are mixed up, see R-script  `RScripts/Main.R` constructing the final report:
`stats_td <- paste0(path_input, sample, "_gd_stats.txt")`
`stats_gd <- paste0(path_input, sample, "_td_stats.txt")`

**Comment by ukf-metzgepa** [comment]
Thank you! I fixed it. Docker release version v2.0.1 or the tag "latest" include the fix already.
