### ISSUE TITLE
Reference genomes encountering errors

### ISSUE THREAD

**Issue by DanielAmsel** [AG-Boerries/MIRACUM-Pipe#15]
https://github.com/AG-Boerries/MIRACUM-Pipe/blob/b5d1c73ff75bb52afd563f6a81d46f51f03a7bdc/Galaxy_Workflows/Galaxy_Subworkflow_MIRACUM_mapped_reads_postprocessing.ga#L249

Here, a different reference genome was specified.
It is not available via `--priviledged` command when using [docker galaxy Exome seq](https://github.com/bgruening/docker-galaxy-exome-seq).

A change from `hg19full` to `hg19`would solve the issue.

**Comment by wm75** [comment]
Yep, will address this, together with the docker image issues in https://github.com/bgruening/docker-galaxy-exome-seq/issues/16, next week. Thanks!

**Comment by wm75** [comment]
Should be fixed. Thanks for reporting.
