### ISSUE TITLE
Change pipeline input

### ISSUE THREAD

**Issue by ukf-metzgepa** [AG-Boerries/MIRACUM-Pipe#2]
Use the complete fastq filenames as input, i.e. 2 files for tumor and 2 files for germline including file extensions.

**Comment by rjschmitt** [comment]
also change docs in https://github.com/AG-Boerries/MIRACUM-Pipe-docker

**Comment by rjschmitt** [comment]
Further this requires editing the `patient.yaml` inside our example on gdrive

**Comment by ukf-metzgepa** [comment]
solved in release v1.0.0
