### ISSUE TITLE
Poorly defined interplay of samtools mpileup -Q & varscan somatic --min-avg-qual options

### ISSUE THREAD

**Issue by wm75** [AG-Boerries/MIRACUM-Pipe#3]
`samtools mpileup` offers the `-Q|--min-BQ` option to exclude reads from the pileup, for which the base aligned to a given site has a low base quality. The default for this option is 13 and the effect is a reduced depth of the generated pileup.
`varscan somatic` has a similar option `--min-avg-qual`, which despite its name, assesses exactly the same property. The default for this option is 15.
However, `varscan somatic` evaluates the base qualities after the `--min-coverage` threshold.

Taken together, the current version of the bash pipeline uses all reads, for which the base quality at a given site surpasses 13 for the pileup at this site. If the resulting depth-of-coverage of either the Normal or the Tumor sample at the site is below `--min-coverage` that site is not considered further. Otherwise,  variant calling gets performed using only the bases from the pileup with a quality of at least 15.

The question is: is a double threshold for base quality (one applied before, one after the coverage threshold) what we want?
Obviously it gives more flexibility than a single parameter and it is the status quo. OTOH, it adds one more parameter to the zoo and it is kind of hard to see why you would base the coverage criterion on reads that you consider too low quality to use them for calling.

**Comment by metzgerpatrick** [comment]
The bigger question is why not setting the base quality directly to 28 in samtools mpileup because in Varscan fpfilter we set the cutoff anyhow to 28. Should save us some computing time and we would be more consistent. I would go with a cutoff as early as possible.
