### ISSUE TITLE
Patient_example not working with version 3.1.0

### ISSUE THREAD

**Issue by nr23730** [AG-Boerries/MIRACUM-Pipe#32]
I just did a run with the `Patient_example` dataset provided with the pipeline.

During the report generation I run into an error as the `quality_check` function referes to a fixed number of lines in `fastqc_data.txt` here: https://github.com/AG-Boerries/MIRACUM-Pipe/blob/development/RScripts/stats_tools.R#L230

I did not ran into this issue with a real dataset but using the test dataset it tried to read the next line `>>END_MODULE` and ran into a problem as it doesn't contain the expected number of columns.

Also the sample dataset should get an update, adding the exon intersected bed file.

**Comment by nr23730** [comment]
Will provide a PR once I verified it's working in the container.

**Comment by ukf-metzgepa** [comment]
Hi Niklas,
I fixed it locally but had no time to implement it here. Managed to do it now.
The function is now more general.

**Comment by nr23730** [comment]
Hi Patrick,
sorry to bother you but I'm currently working on a dataset where this solution does not work. Your assumption is that each row < 10 represents a single readlength while every row > 10 represents two. 

However I have a dataset where this is not true, it looks like this:
`10-14	36.37985197283272	37.0	37.0	37.0	37.0	37.0`

So your approach does not work here, unfortunately. I'm preparing a fix that works by detecting the end of the section.
