### ISSUE TITLE
R Code Update

### ISSUE THREAD

**Issue by ukf-metzgepa** [AG-Boerries/MIRACUM-Pipe#4]
update the current R Code to the latest internal achievements including a refined PDF report.

**Comment by rjschmitt** [comment]
@metzgerpatrick can be closed?

**Comment by ukf-metzgepa** [comment]
unfortunately not yet

**Comment by scheiblr** [comment]
changed milestone to 1.2.0

**Comment by ukf-metzgepa** [comment]
Integrated / updated in release v2.0.0
