### ISSUE TITLE
Missing version history for Galaxy Workflows

### ISSUE THREAD

**Issue by wm75** [AG-Boerries/MIRACUM-Pipe#5]
@scheiblr @metzgerpatrick during the migration of the Galaxy Workflows to the new repo you somehow dropped parts of the workflows version history.
You did not migrate the git history to the new repo and the old history still available at https://github.com/AG-Boerries/MIRACUM-Pipe/commits/master/Galaxy_Workflows is missing its three latest changesets from June 9 - Sep 21.

This is quite unfortunate since these changesets are listed explicitly in confluence, but cannot now be accessed by anyone.

**Comment by wm75** [comment]
cc @bgruening Ok, I've managed to restore the missing changesets by merging a local copy of this repo back into the new one at https://github.com/AG-Boerries/MIRACUM-Pipe-Galaxy, but honestly, this shouldn't have happened in the first place.

**Comment by bgruening** [comment]
Agreed, there is no purpose in using git if such things happen. Thanks for fixing it.

**Comment by ukf-metzgepa** [comment]
Sorry for the inconvenience. Glad to hear you fixed it.
