### ISSUE TITLE
cadd13 database in the annotation protocol

### ISSUE THREAD

**Issue by RitzelC** [AG-Boerries/MIRACUM-Pipe#8]
The cadd13 database has been removed from the annotation protocol.
I do understand that the dbNSFP (~ 30 GB ) does contain a column with cadd13 values, but it is much smaller than the actuall cadd13 database ( ~ 300GB). Is it intended to skip that information?

**Comment by metzgerpatrick** [comment]
We removed it because the CADD v1.3 database is already contained in the dbNSFP database. We were also wondering about the size difference but dbNFSP claims to have all needed information included. But if you wish you can easily add the cadd13 dataset as an additional source for ANNOVAR.
