### ISSUE TITLE
Bug: Onco and suppressor gene annotation

### ISSUE THREAD

**Issue by RitzelC** [AG-Boerries/MIRACUM-Pipe#9]
The function "isogtsg" to annotate the gene status "is_oncogene" or "is_tumorsuppressor" references non-existing columns in the "CancerGenesList.txt" - database.

`isogtsg(x, dbfile = paste(path_data, "CancerGenesList.txt", sep = "/"))` (in filtering.R)
**This results later in empty lists and causes errors in the pdf creation.**

Is there a more recent version of this file?

There is a file available containing such columns under a different location on OncoKB 
(http://oncokb.org/api/v1/utils/allCuratedGenes.txt)

**Comment by metzgerpatrick** [comment]
The function needs the columns "OncoKB Oncogene" and "OncoKB TSG" to work correctly. In the newest release of OncoKB these columns are missing in the downloadable txt file. In version 1.15 it is still available. This file should work: https://github.com/oncokb/oncokb-public/blob/master/data/v1.15/CancerGenesList.txt
